package com.reut.ledger.model

enum class ErrorReason {
    ACCOUNT_DOES_NO_EXISTS,
    CANT_DEPOSIT_AMOUNT_BELOW_ZERO,
    ACCOUNTS_FOR_TRANSACTION_SHOULD_BE_DIFFERENT,
    NOT_ENOUGH_BALANCE_TO_EXECUTE_TRANSACTION,
    CANT_DEPOSIT_TO_INCOME_ACCOUNT,
    UNSUPPORTED_TRANSACTION,
    CANT_CREDIT_EXPENSES_ACCOUNT
}
