package com.reut.ledger.core

enum class ErrorReason {
    ACCOUNT_DOES_NO_EXISTS,
    FINAL_BALANCE_IS_TO_BIG,
    CANT_DEPOSIT_AMOUNT_BELOW_ZERO,
    NOT_ENOUGH_BALANCE_TO_EXECUTE_TRANSACTION,
    ACCOUNT_BALANCE_IS_BELOW_ZERO
}
